### ISSUE TITLE
FileNotFoundError in process_standalone_experiment.py

### ISSUE THREAD

**Issue by sethb3744** [linnarsson-lab/pysmFISH#4]
Hi Simone,

Thanks again for your help in working through pysmFISH so far! Now that I've finished the installation, I tried a test run of process_standalone_experiment.py with a random sample .nd2 file that I found online. However, I ran into an issue where a file created by numpy could not be found. I tried this with numpy versions 1.15.4 and 1.14.6, but neither worked. Are either of those the versions you used? I have copied the error below and bolded the parts I thought were important. In case it is useful, you can find the sample .nd2 file I found at the following link: https://s3-us-west-1.amazonaws.com/shen-sbergenholtz/bigWigs/BF007.nd2

Traceback (most recent call last):
File "process_standalone_experiment.py", line 170, in 
process_standalone_experiment()
File "process_standalone_experiment.py", line 143, in process_standalone_experiment
np.save(converted_fname,img_stack,allow_pickle=False)
File "/netapp/home/sethberg/dependencies/miniconda3/lib/python3.7/site-packages/numpy/lib/npyio.py", line 492, in save
fid = open(file, "wb")
FileNotFoundError: [Errno 2] No such file or directory: '/shen/shenlabstore2/sethberg/dependencies/pysmFISH/test_Jan17/test_Jan17_test_Jan17_tmp/test_Jan17_BF007_405/488/561/633nm_fov_0.npy'
distributed.process - WARNING - reaping stray process <ForkServerProcess(ForkServerProcess-1, started daemon)>
distributed.nanny - WARNING - Worker process 20216 was killed by signal 15
Traceback (most recent call last):
File "/netapp/home/sethberg/dependencies/miniconda3/lib/python3.7/multiprocessing/util.py", line 265, in _run_finalizers
finalizer()
File "/netapp/home/sethberg/dependencies/miniconda3/lib/python3.7/multiprocessing/util.py", line 189, in call
res = self._callback(*self._args, **self._kwargs)
File "/netapp/home/sethberg/dependencies/miniconda3/lib/python3.7/shutil.py", line 489, in rmtree
onerror(os.rmdir, path, sys.exc_info())
File "/netapp/home/sethberg/dependencies/miniconda3/lib/python3.7/shutil.py", line 487, in rmtree
os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/scrapp/for_seth/tmpdir/pymp-2w1mvwwi'

Also, the most recent update of numpy (1.16.0) has a bug that makes it unusable with pysmFISH. This is not part of my issue, but I wanted to let you know. In your setup.py file, you might want to indicate the version of numpy that should be installed is 1.15.4 (or whichever version you used) until those bugs are fixed.

Best,
Seth

**Comment by sethb3744** [comment]
I'm not sure what caused the original issue, but the version of the file with tiff conversion that I put together is working correctly with np.save for some reason. It still has the final error, copied at the bottom, which is caused by the line: shutil.rmtree(tmp_dir_path). This is not a big issue though, since I can just delete the tmp_dir myself.

You still might want to address the numpy bug I mentioned in my last comment, though.

Traceback (most recent call last):
File "/netapp/home/sethberg/dependencies/miniconda3/lib/python3.7/multiprocessing/util.py", line 265, in _run_finalizers
finalizer()
File "/netapp/home/sethberg/dependencies/miniconda3/lib/python3.7/multiprocessing/util.py", line 189, in call
res = self._callback(*self._args, **self._kwargs)
File "/netapp/home/sethberg/dependencies/miniconda3/lib/python3.7/shutil.py", line 489, in rmtree
onerror(os.rmdir, path, sys.exc_info())
File "/netapp/home/sethberg/dependencies/miniconda3/lib/python3.7/shutil.py", line 487, in rmtree
os.rmdir(path)
OSError: [Errno 39] Directory not empty: '/scrapp/for_seth/tmpdir/pymp-2w1mvwwi'
